name: Upload to sourceforge
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SF_USERNAME: ${{ secrets.SF_USER }}
  SF_PASSWORD: ${{ secrets.SF_PASWORD }}
  LINK: https://nfsproject.projek.workers.dev/0:/RiceDroid/rosy/riceDroid-12.1-2022080917-rosy-v4.5-PIXEL.zip
  UPLOAD: ricedroid-rosy/12

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo & checkout code
      uses: actions/checkout@v2

    - name: SSH agent
      uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
        key_file: frs.sourceforge.net

    - name: Download..
      run: |
        wget ${LINK}

    - name: Upload..
      run: |
        sshpass -p ${SF_PASSWORD} scp *.zip ${SF_USERNAME}@frs.sourceforge.net:/home/frs/project/${UPLOAD}
